title: wqhyw's blog
email: wqhyw2@gmail.com
description: Long may the sun shine!
baseurl: /blog
# url: "https://wqhyw.github.io"
github_username:  wqhyw

plugins:
  - jekyll-archives

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: contrast
search: true
search_full_content: true
breadcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"
permalink: /:categories/:title
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      toc: true
      toc_icon: "align-justify"
      toc_label: 目录

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
