title: Redis Reading
email: wqhyw2@gmail.com
description: Redis source code notes
# baseurl: "/redis_reading"
# url: "https://wqhyw.github.io"
github_username:  wqhyw

plugins:
  - jekyll-spaceship
  - jekyll-archives

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: dirt
search: true
search_full_content: true
breadcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"

# jekyll-spaceship config
jekyll-spaceship:
  processors:
    - mermaid-processor
  mermaid-processor:
    mode: pre-fetch
    syntax:
      code: 'mermaid'
  config:
    theme: neutral

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      toc: true
      toc_label: "Table of Contents"
      toc_icon: "cog"
      sidebar:
        nav: "side-nav"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
